#ifndef DATATYPE_H
#define DATATYPE_H

namespace mpxjpp {

enum class DataType {
	__UNINITIALIZED__ = 0,

	STRING = 1,
	DATE = 2,
	CURRENCY = 3,
	BOOLEAN = 4,
	NUMERIC = 5,
	DURATION = 6,
	UNITS = 7,
	PERCENTAGE = 8,
	ACCRUE = 9,
	CONSTRAINT = 10,
	RATE = 11,
	PRIORITY = 12,
	RELATION_LIST = 13,
	TASK_TYPE = 14,
	RESOURCE_TYPE = 15,
	WORK = 16,
	INTEGER = 17,
	ASCII_STRING = 18,
	SHORT = 19,
	BINARY = 20,
	DELAY = 21,
	WORK_UNITS = 22,
	WORKGROUP = 23,
	GUID = 24,
	RATE_UNITS = 25,
	EARNED_VALUE_METHOD = 26,
	RESOURCE_REQUEST_TYPE = 27,
	CURRENCY_SYMBOL_POSITION = 28,
	CHAR = 29,
	DATE_ORDER = 30,
	PROJECT_TIME_FORMAT = 31,
	PROJECT_DATE_FORMAT = 32,
	SCHEDULE_FROM = 33,
	DAY = 34,
	MAP = 35,
	MPX_FILE_VERSION = 36,
	MPX_CODE_PAGE = 37,
	BOOKING_TYPE = 38,
	TIME_UNITS = 39
};

}

#endif // DATATYPE_H
