#ifndef PROJECTFIELD_H
#define PROJECTFIELD_H

#include "fieldtype.h"

namespace mpxjpp {

struct ProjectField final : public FieldType {

#define PROJECT_FIELD_GEN(F) \
	F(START_DATE, DataType::DATE),\
	\
	F(CURRENCY_SYMBOL, DataType::STRING),\
	F(CURRENCY_SYMBOL_POSITION, DataType::CURRENCY_SYMBOL_POSITION),\
	F(CURRENCY_DIGITS, DataType::INTEGER),\
	F(THOUSANDS_SEPARATOR, DataType::CHAR),\
	F(DECIMAL_SEPARATOR, DataType::CHAR),\
	F(DEFAULT_DURATION_UNITS, DataType::TIME_UNITS),\
	F(DEFAULT_DURATION_IS_FIXED, DataType::BOOLEAN),\
	F(DEFAULT_WORK_UNITS, DataType::TIME_UNITS),\
	F(DEFAULT_STANDARD_RATE, DataType::RATE),\
	F(DEFAULT_OVERTIME_RATE, DataType::RATE),\
	F(UPDATING_TASK_STATUS_UPDATES_RESOURCE_STATUS, DataType::BOOLEAN),\
	F(SPLIT_IN_PROGRESS_TASKS, DataType::BOOLEAN),\
	F(DATE_ORDER, DataType::DATE_ORDER),\
	F(TIME_FORMAT, DataType::PROJECT_TIME_FORMAT),\
	F(DEFAULT_START_TIME, DataType::DATE),\
	F(DATE_SEPARATOR, DataType::CHAR),\
	F(TIME_SEPARATOR, DataType::CHAR),\
	F(AM_TEXT, DataType::STRING),\
	F(PM_TEXT, DataType::STRING),\
	F(DATE_FORMAT, DataType::PROJECT_DATE_FORMAT),\
	F(BAR_TEXT_DATE_FORMAT, DataType::PROJECT_DATE_FORMAT),\
	F(PROJECT_TITLE, DataType::STRING),\
	F(COMPANY, DataType::STRING),\
	F(MANAGER, DataType::STRING),\
	F(DEFAULT_CALENDAR_NAME, DataType::STRING),\
	F(SCHEDULE_FROM, DataType::SCHEDULE_FROM),\
	F(CURRENT_DATE, DataType::DATE),\
	F(COMMENTS, DataType::STRING),\
	F(COST, DataType::CURRENCY),\
	F(BASELINE_COST, DataType::CURRENCY),\
	F(ACTUAL_COST, DataType::CURRENCY),\
	F(WORK, DataType::WORK),\
	F(BASELINE_WORK, DataType::WORK),\
	F(ACTUAL_WORK, DataType::WORK),\
	F(WORK2, DataType::NUMERIC),\
	F(DURATION, DataType::DURATION),\
	F(BASELINE_DURATION, DataType::DURATION),\
	F(ACTUAL_DURATION, DataType::DURATION),\
	F(PERCENTAGE_COMPLETE, DataType::PERCENTAGE),\
	F(BASELINE_START, DataType::DATE),\
	F(BASELINE_FINISH, DataType::DATE),\
	F(ACTUAL_START, DataType::DATE),\
	F(ACTUAL_FINISH, DataType::DATE),\
	F(START_VARIANCE, DataType::DURATION),\
	F(FINISH_VARIANCE, DataType::DURATION),\
	F(SUBJECT, DataType::STRING),\
	F(AUTHOR, DataType::STRING),\
	F(KEYWORDS, DataType::STRING),\
	F(HYPERLINK_BASE, DataType::STRING),\
	F(DEFAULT_END_TIME, DataType::DATE),\
	F(PROJECT_EXTERNALLY_EDITED, DataType::BOOLEAN),\
	F(CATEGORY, DataType::STRING),\
	F(MINUTES_PER_DAY, DataType::INTEGER),\
	F(DAYS_PER_MONTH, DataType::INTEGER),\
	F(MINUTES_PER_WEEK, DataType::INTEGER),\
	F(FISCAL_YEAR_START, DataType::BOOLEAN),\
	F(DEFAULT_TASK_EARNED_VALUE_METHOD, DataType::EARNED_VALUE_METHOD),\
	F(REMOVE_FILE_PROPERTIES, DataType::BOOLEAN),\
	F(MOVE_COMPLETED_ENDS_BACK, DataType::BOOLEAN),\
	F(NEW_TASKS_ESTIMATED, DataType::BOOLEAN),\
	F(SPREAD_ACTUAL_COST, DataType::BOOLEAN),\
	F(MULTIPLE_CRITICAL_PATHS, DataType::BOOLEAN),\
	F(AUTO_ADD_NEW_RESOURCES_AND_TASKS, DataType::BOOLEAN),\
	F(LAST_SAVED, DataType::DATE),\
	F(STATUS_DATE, DataType::DATE),\
	F(MOVE_REMAINING_STARTS_BACK, DataType::BOOLEAN),\
	F(AUTO_LINK, DataType::BOOLEAN),\
	F(MICROSOFT_PROJECT_SERVER_URL, DataType::BOOLEAN),\
	F(HONOR_CONSTRAINTS, DataType::BOOLEAN),\
	F(ADMIN_PROJECT, DataType::BOOLEAN),\
	F(INSERTED_PROJECTS_LIKE_SUMMARY, DataType::BOOLEAN),\
	F(NAME, DataType::STRING),\
	F(SPREAD_PERCENT_COMPLETE, DataType::BOOLEAN),\
	F(MOVE_COMPLETED_ENDS_FORWARD, DataType::BOOLEAN),\
	F(EDITABLE_ACTUAL_COSTS, DataType::BOOLEAN),\
	F(UNIQUE_ID, DataType::STRING),\
	F(REVISION, DataType::INTEGER),\
	F(NEW_TASKS_EFFORT_DRIVEN, DataType::BOOLEAN),\
	F(MOVE_REMAINING_STARTS_FORWARD, DataType::BOOLEAN),\
	F(ACTUALS_IN_SYNC, DataType::BOOLEAN),\
	F(DEFAULT_TASK_TYPE, DataType::TASK_TYPE),\
	F(EARNED_VALUE_METHOD, DataType::EARNED_VALUE_METHOD),\
	F(CREATION_DATE, DataType::DATE),\
	F(EXTENDED_CREATION_DATE, DataType::DATE),\
	F(DEFAULT_FIXED_COST_ACCRUAL, DataType::ACCRUE),\
	F(CRITICAL_SLACK_LIMIT, DataType::INTEGER),\
	F(BASELINE_FOR_EARNED_VALUE, DataType::INTEGER),\
	F(FISCAL_YEAR_START_MONTH, DataType::INTEGER),\
	F(NEW_TASK_START_IS_PROJECT_START, DataType::BOOLEAN),\
	F(WEEK_START_DAY, DataType::DAY),\
	F(CALCULATE_MULTIPLE_CRITICAL_PATHS, DataType::BOOLEAN),\
	F(CUSTOM_PROPERTIES, DataType::MAP),\
	F(CURRENCY_CODE, DataType::STRING),\
	F(SHOW_PROJECT_SUMMARY_TASK, DataType::BOOLEAN),\
	F(BASELINE_DATE, DataType::DATE),\
	F(BASELINE1_DATE, DataType::DATE),\
	F(BASELINE2_DATE, DataType::DATE),\
	F(BASELINE3_DATE, DataType::DATE),\
	F(BASELINE4_DATE, DataType::DATE),\
	F(BASELINE5_DATE, DataType::DATE),\
	F(BASELINE6_DATE, DataType::DATE),\
	F(BASELINE7_DATE, DataType::DATE),\
	F(BASELINE8_DATE, DataType::DATE),\
	F(BASELINE9_DATE, DataType::DATE),\
	F(BASELINE10_DATE, DataType::DATE),\
	F(TEMPLATE, DataType::STRING),\
	F(LAST_AUTHOR, DataType::STRING),\
	F(LASTPRINTED, DataType::DATE),\
	F(SHORT_APPLICATION_NAME, DataType::STRING),\
	F(EDITING_TIME, DataType::INTEGER),\
	F(PRESENTATION_FORMAT, DataType::STRING),\
	F(CONTENT_TYPE, DataType::STRING),\
	F(CONTENT_STATUS, DataType::STRING),\
	F(LANGUAGE, DataType::STRING),\
	F(DOCUMENT_VERSION, DataType::STRING),\
	F(MPX_DELIMITER, DataType::CHAR),\
	F(MPX_PROGRAM_NAME, DataType::STRING),\
	F(MPX_FILE_VERSION, DataType::MPX_FILE_VERSION),\
	F(MPX_CODE_PAGE, DataType::MPX_CODE_PAGE),\
	F(PROJECT_FILE_PATH, DataType::STRING),\
	F(FULL_APPLICATION_NAME, DataType::STRING),\
	F(APPLICATION_VERSION, DataType::INTEGER),\
	F(MPP_FILE_TYPE, DataType::INTEGER),\
	F(AUTOFILTER, DataType::BOOLEAN),\
	F(FILE_APPLICATION, DataType::STRING),\
	F(FILE_TYPE, DataType::STRING),\
	\
	F(FINISH_DATE, DataType::DATE),\


public:
	enum Fields {
		PROJECT_FIELD_GEN(MPXJPP_GEN_ENUM)
	};
private:
	static struct FieldType::priv_field_t g_fields[];
	static struct FieldType::priv_arr_t g_class;
public:
	constexpr ProjectField(int val) :
		FieldType(val, &g_class)
	{}
};

}
#endif // PROJECTFIELD_H
